// Code generated by mockery v2.40.1. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// MockConfigurer is an autogenerated mock type for the Configurer type
type MockConfigurer struct {
	mock.Mock
}

// GetConfig provides a mock function with given fields:
func (_m *MockConfigurer) GetConfig() (Config, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 Config
	var r1 error
	if rf, ok := ret.Get(0).(func() (Config, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Config)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockConfigurer creates a new instance of MockConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurer {
	mock := &MockConfigurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
