name: CI

on:
  push:
    branches:
      - "*"

jobs:
  test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - run: go version
      - run: go get
      - run: go test -v ./...
  build-check:
    name: "Build"
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - run: go version
      - run: go get
      - run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build .
